### ISSUE TITLE
Trying to build GoASQ following the directions and I keep getting build errors.

### ISSUE THREAD

**Issue by pblanton** [Morningstar/GoASQ#6]
I've solved most of them, but this one is particularly vexing...

_"Failed building wheel for pysqlite"_

Here's the error screenshot...

![image](https://user-images.githubusercontent.com/1143649/48450507-a1f88f00-e763-11e8-8690-c499585a3d4d.png)

And a little further down at the end...

![image](https://user-images.githubusercontent.com/1143649/48450513-af157e00-e763-11e8-8a6a-16e3d2b5bc30.png)

Sqlite 3 is installed and the latest version.

**Comment by yippibrian** [comment]
The GNU compiler is clearly not finding the sqlite3.h header file.  Where header files get installed is very dependent on what OS you are using.  Is the sqlite3.h header file in a standard include location (/usr/local/include/ or /usr/include/)

If not, you could set environment variables to help gcc find it.
http://www.network-theory.co.uk/docs/gccintro/gccintro_23.html

**Comment by pblanton** [comment]
I figured all of that out. I can build the app now but I have to edit do.sh to remove the database setup code in order to get the build to run. 

To fix my sqlite3 issues I did this...

_Installed sqlite3
	Get sqlite3 from http://www.sqlite.org/sqlite-3.6.4.tar.gz
	extract it to /usr/lib/sqlite3
	build and install it like this...
		sudo ./configure && sudo make install
		sudo apt install sqlite
		sudo -H pip install ydk-models-cisco-ios-xr_

To build, I edited do.sh and commented out lines 170-172 in  `vsaq_build()` so that the build would run. 

That's because I am getting the following error...

`Setting up DB in build/db
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "db_setup.py", line 14, in <module>
    import datetime, fnmatch, json, os, random, string, sqlite3
  File "/usr/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python2.7/lib-dynload/_sqlite3.x86_64-linux-gnu.so: undefined symbol: sqlite3_enable_load_extension`

Now that I have deployed the app (running with an Apache root symlink pointing to the `build` directory) I need to run the setup_db code. Any ideas how to get past the `undefined symbol: sqlite3_enable_load_extension` error?

**Comment by pblanton** [comment]
I have the wrong version of sqlite lurking somewhere on my Ubuntu 18.04. It is version 2.8.17. I just determined that by running `sqlite -version` but haven't figured out how to replace it with version 3.6.4 yet.

**Comment by pblanton** [comment]
I worked through the issues but not before building a new Ubuntu dev VM. Something on the first one was hosed and nothing I could do would overcome it. I snapshotted the second machine so I could roll it back in the event it got into the same state, but didn't need to because I had no real issues this time through.
